#! /bin/sh

# find all java source files in src directory
FILES=$(find src -iname "*.java")

rm -rf bin
mkdir -p bin

echo "Building Maze Game..."
echo "Compiling source code..."

# compile each source file into bin directory, exiting on compilation failure
for file in $FILES
do
    echo "Compiling: $file"
    javac -cp "./src/" -d bin $file
    if [ $? -ne 0 ]
    then
        exit 1
    fi
done

echo "Source code compilation succeeded"

echo "Copying resources..."

cp menu-background.png bin/menu-background.png
cp fog.png bin/fog.png
cp mountain_king.wav bin/mountain_king.wav

echo "Copying resources succeeded"
echo ""

echo "Build successful."
